server:
  port: 3364   #纪念给予我最大支持的老婆 DENG 对应九宫格编码 '3364'
spring:
  datasource:
    url: jdbc:mysql://192.168.245.133:33306/sd
    username: root
    password: Admin123.
    driver-class-name: com.mysql.cj.jdbc.Driver

swagger:
  production: false
